"""baseline schema

Revision ID: e368e83c0b4c
Revises: 
Create Date: 2026-09-05 15:13:06.190786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e368e83c0b4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_rating',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('strong_buy', sa.Integer(), nullable=True),
    sa.Column('buy', sa.Integer(), nullable=True),
    sa.Column('hold', sa.Integer(), nullable=True),
    sa.Column('sell', sa.Integer(), nullable=True),
    sa.Column('strong_sell', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'period')
    )
    op.create_table('asset',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('earnings_calendar',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('hour', sa.String(length=8), nullable=True),
    sa.Column('eps_estimate', sa.Numeric(), nullable=True),
    sa.Column('eps_actual', sa.Numeric(), nullable=True),
    sa.Column('revenue_estimate', sa.BigInteger(), nullable=True),
    sa.Column('revenue_actual', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'report_date')
    )
    op.create_table('ingest_run',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('job', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rows_upserted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('api_calls_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ingest_run_source_time', 'ingest_run', ['source', 'started_at'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('news_symbol_time', 'news', ['symbol', 'published_at'], unique=False)
    op.create_table('series',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=4), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_series_source_ext')
    )
    op.create_table('observation',
    sa.Column('series_id', sa.BigInteger(), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('series_id', 'obs_date')
    )
    op.create_index('observation_date_brin', 'observation', ['obs_date'], unique=False, postgresql_using='brin')
    op.create_table('price_daily',
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=False),
    sa.Column('high', sa.Numeric(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'trade_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_daily')
    op.drop_index('observation_date_brin', table_name='observation', postgresql_using='brin')
    op.drop_table('observation')
    op.drop_table('series')
    op.drop_index('news_symbol_time', table_name='news')
    op.drop_table('news')
    op.drop_index('ingest_run_source_time', table_name='ingest_run')
    op.drop_table('ingest_run')
    op.drop_table('earnings_calendar')
    op.drop_table('asset')
    op.drop_table('analyst_rating')
    # ### end Alembic commands ###
