import { describe, expect, it, vi } from "vitest";

import worker, { JOB_BY_CRON, sign, triggerIngest, type Env } from "../src/index";

const ENV: Env = {
  API_BASE_URL: "https://api.example",
  INGEST_HMAC_SECRET: "test-secret",
};

describe("sign", () => {
  it("matches the vector produced by marketpulse.core.security.sign", async () => {
    // Generated by the Python implementation the API verifies with:
    //   sign("test-secret", "1757700000", "macro")
    // If this fails, the two languages have drifted and every trigger 401s.
    const signature = await sign("test-secret", "1757700000", "macro");
    expect(signature).toBe(
      "54a9654e6c1dd054d0a0328492583d05957f08af585932addb78cdba582121e5",
    );
  });

  it("signs the timestamp and source together, not separately", async () => {
    // Swapping the pair must change the digest, or a captured signature could
    // be replayed against a different job.
    const a = await sign("s", "1757700000", "macro");
    const b = await sign("s", "1757700000", "prices");
    expect(a).not.toBe(b);
  });
});

describe("triggerIngest", () => {
  it("posts to the job's endpoint with both signature headers", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValue(new Response(null, { status: 202 }));
    vi.stubGlobal("fetch", fetchMock);

    await triggerIngest(ENV, "macro");

    const [url, init] = fetchMock.mock.calls[0];
    expect(url).toBe("https://api.example/internal/ingest/macro");
    expect(init.method).toBe("POST");

    const timestamp = init.headers["X-Timestamp"];
    expect(timestamp).toMatch(/^\d+$/);
    expect(init.headers["X-Signature"]).toBe(
      await sign(ENV.INGEST_HMAC_SECRET, timestamp, "macro"),
    );

    vi.unstubAllGlobals();
  });

  it("throws with the response body so a 401 is not mistaken for a bad URL", async () => {
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue(
        new Response('{"detail":"unauthorized"}', { status: 401 }),
      ),
    );

    await expect(triggerIngest(ENV, "macro")).rejects.toThrow(/401.*unauthorized/);

    vi.unstubAllGlobals();
  });
});

describe("scheduled", () => {
  function context() {
    const promises: Promise<unknown>[] = [];
    return {
      // Only waitUntil is exercised here; the rest of ExecutionContext is
      // irrelevant to routing, so the cast goes through unknown.
      ctx: {
        waitUntil: (p: Promise<unknown>) => {
          promises.push(p);
        },
      } as unknown as ExecutionContext,
      settled: () => Promise.allSettled(promises),
    };
  }

  it("routes each cron expression to its job", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValue(new Response(null, { status: 202 }));
    vi.stubGlobal("fetch", fetchMock);

    const cases: Array<[string, string]> = [
      ["15 13 * * *", "macro"],
      ["30 15 * * 1-5", "fx"],
      ["0 22 * * 1-5", "prices"],
      ["0 */6 * * *", "crypto"],
      ["10 */6 * * *", "news"],
      ["0 23 * * *", "earnings"],
      ["0 4 * * 1", "ratings"],
    ];

    for (const [cron, job] of cases) {
      fetchMock.mockClear();
      const { ctx, settled } = context();
      await worker.scheduled({ cron } as ScheduledController, ENV, ctx);
      await settled();
      expect(fetchMock.mock.calls[0][0]).toBe(
        `https://api.example/internal/ingest/${job}`,
      );
    }

    vi.unstubAllGlobals();
  });

  it("maps every job the API exposes, and nothing it does not", () => {
    // JOB_NAMES in marketpulse/ingest/jobs.py. A job with no trigger never
    // runs; a job name with a typo 404s on every fire. Compare the names
    // themselves — comparing counts would pass in both cases.
    const jobs = ["crypto", "earnings", "fx", "macro", "news", "prices", "ratings"];
    expect([...new Set(Object.values(JOB_BY_CRON))].sort()).toEqual(jobs);
  });

  it("gives every cron expression a distinct job", () => {
    // Cloudflare identifies a trigger only by its expression, so a duplicate
    // expression silently drops one of the two jobs. Spec 5.2 gives crypto and
    // news the same "0 */6 * * *"; news is offset by ten minutes here.
    const expressions = Object.keys(JOB_BY_CRON);
    expect(new Set(expressions).size).toBe(expressions.length);
    expect(new Set(Object.values(JOB_BY_CRON)).size).toBe(expressions.length);
  });

  it("logs and makes no request when a cron expression has no mapping", async () => {
    const fetchMock = vi.fn();
    vi.stubGlobal("fetch", fetchMock);
    const errors = vi.spyOn(console, "error").mockImplementation(() => {});

    const { ctx, settled } = context();
    await worker.scheduled({ cron: "* * * * *" } as ScheduledController, ENV, ctx);
    await settled();

    expect(fetchMock).not.toHaveBeenCalled();
    expect(errors).toHaveBeenCalledWith(
      'no job mapped to cron expression "* * * * *"',
    );

    errors.mockRestore();
    vi.unstubAllGlobals();
  });
});
